name: example_app
description: Flutter app or dart package.
publish_to: "none"

version: 1.1.1+200

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
