name: Create release pull request

on:
  workflow_call:
    inputs:
      version:
        description: "リリースバージョン（例: 1.0.0）\n未指定の場合はビルド番号のみインクリメント。"
        required: false
        type: string
      working-directory:
        description: "モノレポの場合はをディレクトリを指定する"
        default: "./"
        type: string
    secrets:
      app-id:
        description: "GitHub App ID"
        required: true
      private-key:
        description: "GitHub App private key"
        required: true

jobs:
  # リリースバージョンとブランチ名を設定する。
  set-version-and-branch-name:
    name: Set version and branch name
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-output.outputs.version }}
      branch_name: ${{ steps.set-output.outputs.branch_name }}
    steps:
      - uses: actions/checkout@v3

      # リリースバージョンが入力されている場合は入力されたバージョンを環境変数に設定する。
      - name: Set input version to GITHUB_ENV
        if: ${{ inputs.version }}
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      # リリースバージョンが入力されていない場合は現在のバージョンを環境変数に設定する。
      - name: Set current version to GITHUB_ENV
        if: ${{ !inputs.version }}
        run: |
          version=$(perl -ne 'print $1 if /^version:\s+(\d+\.\d+\.\d+)/' pubspec.yaml)
          echo "VERSION=${version}" >> $GITHUB_ENV
        working-directory: ${{ inputs.working-directory }}

      # リリースブランチ名を環境変数に設定する。
      - name: Set branch name to GITHUB_OUTPUT
        run: |
          branch_name="release/${{ env.VERSION }}"
          echo "BRANCH_NAME=${branch_name}" >> $GITHUB_ENV

      # リリースバージョンとリリースブランチ名を出力変数に設定する。
      - name: Set version and branch name to GITHUB_OUTPUT
        id: set-output
        run: |
          echo "version=${{ env.VERSION }} " >> "$GITHUB_OUTPUT"
          echo "branch_name=${{ env.BRANCH_NAME }} " >> "$GITHUB_OUTPUT"

  # リリースブランチを作成する。
  create-release-branch:
    name: Create release branch
    runs-on: ubuntu-latest
    needs: [set-version-and-branch-name]
    steps:
      - uses: actions/checkout@v3

      # ブランチ名を環境変数に設定する。
      - name: Set branch name to GITHUB_ENV
        run: |
          echo "BRANCH_NAME=${{ needs.set-version-and-branch-name.outputs.branch_name }}" >> $GITHUB_ENV

      # リリースブランチがすでに存在するかどうかを判定し、結果を環境変数に設定する。
      - name: Set whether the branch is already existing to GITHUB_ENV
        run: |
          branch_is_existing=$(
            git fetch origin ${{ env.BRANCH_NAME }} &&
            echo true ||
            echo false
          )
          echo "BRANCH_IS_EXISTING=${branch_is_existing}" >> $GITHUB_ENV

      # リリースブランチが存在しない場合は作成する。
      - name: Create release branch
        if: env.BRANCH_IS_EXISTING == 'false'
        run: |
          git switch -c ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}

  # バージョン番号とビルド番号を上げる。
  bump-version:
    name: Bump version and build number
    runs-on: ubuntu-latest
    needs: [set-version-and-branch-name, create-release-branch]
    steps:
      - uses: actions/checkout@v3

      # バージョンとブランチ名を環境変数に設定する。
      - name: Set version and branch name to GITHUB_ENV
        run: |
          echo "VERSION=${{ needs.set-version-and-branch-name.outputs.version }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ needs.set-version-and-branch-name.outputs.branch_name }}" >> $GITHUB_ENV

      # 作成したリリースブランチに切り替える。
      - name: Switch branch
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}
          git switch ${{ env.BRANCH_NAME }}

      # バージョン番号とビルド番号を上げる。
      - name: Bump version and build number
        run: |
          VERSION=${{ env.VERSION }}
          perl -i -pse 's/^(version:\s)+\d+\.\d+\.\d+\+(\d+)$/$1.$version.($2+1)/e' -- -version=${VERSION}+ pubspec.yaml
        working-directory: ${{ inputs.working-directory }}

      # 変更差分があるかどうかを判定し、結果を環境変数に設定する。
      - name: Check diff
        run: |
          diff_count=$(git diff | wc -l)
          echo "DIFF_COUNT=${diff_count}" >> $GITHUB_ENV

      # 変更差分がある場合はコミットするためのGitの設定を行う。
      - name: Git config
        if: env.DIFF_COUNT != '0'
        run: |
          git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # 変更差分がある場合はコミットする。
      - name: Commit & Push
        if: env.DIFF_COUNT != '0'
        run: |
          git add .
          git commit -m "Bump version and build number"
          git push origin ${{ env.BRANCH_NAME }}

  # Pull-Requestを作成する。
  create-pr:
    name: Create Pull-Request for release
    runs-on: ubuntu-latest
    needs: [set-version-and-branch-name, bump-version]
    steps:
      - uses: actions/checkout@v3

      # ブランチ名を環境変数に設定する。
      - name: Set branch name to GITHUB_ENV
        run: |
          echo "BRANCH_NAME=${{ needs.set-version-and-branch-name.outputs.branch_name }}" >> $GITHUB_ENV

      # GitHub Appのトークンを生成する。
      - name: Generate GiHub App token
        id: generate
        run: |
          #!/usr/bin/env bash
          # Base64URLエンコード関数
          base64url() {
            openssl enc -base64 -A | tr '+/' '-_' | tr -d '='
          }          
          # 署名する関数
          sign() {
            openssl dgst -binary -sha256 -sign <(printf '%s' "${{ secrets.private-key }}")
          }
          # JWTのヘッダー
          header="$(printf '{"alg":"RS256","typ":"JWT"}' | base64url)"
          # JWTのペイロード
          now="$(date '+%s')"
          iat="$((now - 60))"
          exp="$((now + (3 * 60)))"
          template='{"iss":"%s","iat":%s,"exp":%s}'
          payload="$(printf "${template}" "${{ secrets.app-id }}" "${iat}" "${exp}" | base64url)"
          echo "::add-mask::${payload}"
          # JWTの署名
          signature="$(printf '%s' "${header}.${payload}" | sign | base64url)"
          echo "::add-mask::${signature}"
          # JWTの生成
          jwt="${header}.${payload}.${signature}"
          echo "::add-mask::${jwt}"
          # Installation ID を取得
          installation_id="$(curl --location --silent --request GET \
            --url "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/installation" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${jwt}" \
            | jq -r '.id'
          )"
          # アクションを実行するリポジトリ名を取得
          repo_name="$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)"
          # アクセストークンを生成
          token="$(curl --location --silent --request POST \
            --url "${GITHUB_API_URL}/app/installations/${installation_id}/access_tokens" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${jwt}" \
            --data "$(printf '{"repositories":["%s"]}' "${repo_name}")" \
            | jq -r '.token'
          )"
          echo "::add-mask::${token}"
          echo "token=${token}" >> $GITHUB_OUTPUT
        shell: bash

      # mainブランチ向けにPull-Requestを作成する。
      - name: Create release PR to main
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: gh pr create -B "main" -t ${{ env.BRANCH_NAME }} -b "" -a $GITHUB_ACTOR -H ${{ env.BRANCH_NAME }}

      # GitHub Appのトークンを失効させる。
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
